version: "3.9"

services:
  demo-bot:
    build: .                 
    image: demo-personal-bot 
    container_name: demo-ai-bot
    restart: unless-stopped
    env_file: .env        
    command: npm start
    ports:
      - "3002:3000"
    volumes:
      - .:/app               
      - /app/node_modules   
